[package]
name = "peanut"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
duct = "1.1.1"
iced = { version = "0.14.0", features = ["tokio", "debug"] }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
url = "2.5.7"
